import {
  AlertCircle,
  Box,
  ChevronUp,
  ChevronsUpDown,
  File,
  FileDown,
  FileInput,
  FilePlus,
  ExternalLink,
  FileText,
  Files,
  FolderInput,
  FolderOutput,
  LoaderCircle,
  Mail,
  MailPlus,
  Maximize,
  Moon,
  MoreHorizontal,
  PanelLeft,
  Pencil,
  PenLine,
  Plus,
  RefreshCw,
  Save,
  Search,
  Settings,
  Sun,
  Trash2,
  User,
  UserPlus,
  X,
  ZoomIn,
  ZoomOut,
} from "lucide-react";

export const Icons = {
  currentUser: User,
  switchUser: ChevronsUpDown,
  createUser: UserPlus,
  renameUser: PenLine,
  importUser: FolderInput,
  exportUser: FolderOutput,
  search: Search,
  createVariant: Plus,
  deleteUnsaved: Trash2,
  versionMenu: MoreHorizontal,
  importHtml: FileInput,
  variant: Box,
  version: Files,
  draft: Pencil,
  resume: FileText,
  coverLetter: Mail,
  additional: File,
  addCoverLetter: MailPlus,
  addDocument: FilePlus,
  save: Save,
  exportPdf: FileDown,
  close: X,
  emptyCreate: Plus,
  emptyImport: FileInput,
  sidebar: PanelLeft,
  error: AlertCircle,
  busy: LoaderCircle,
  zoomIn: ZoomIn,
  zoomOut: ZoomOut,
  fit: Maximize,
  themeLight: Sun,
  themeDark: Moon,
  settings: Settings,
  sync: RefreshCw,
  openLink: ExternalLink,
  chevronUp: ChevronUp,
};
